const fs = require('fs');
let text = fs.readFileSync('admin.html', 'utf8').replace(/\r\n/g, '\n');

const s1 = '<div class="form-group">\n                        <label for="eventLocation">Location</label>\n                        <input type="text" id="eventLocation" value="Barangay Basketball Court" required>\n                    </div>';
const r1 = s1 + '\n                    <div class="form-group">\n                        <label for="eventDescription">Event Details (Description)</label>\n                        <textarea id="eventDescription" placeholder="e.g., Free vaccine drive for residents" rows="3"></textarea>\n                    </div>\n                    <div class="form-group">\n                        <label for="eventCapacity">Maximum Capacity Limit</label>\n                        <input type="number" id="eventCapacity" placeholder="Leave empty or 0 for unlimited" min="0">\n                    </div>';
text = text.replace(s1, r1);

const s2 = '<div class="form-group">\n                        <label for="editEventLocation">Location</label>\n                        <input type="text" id="editEventLocation" required>\n                    </div>';
const r2 = s2 + '\n                    <div class="form-group">\n                        <label for="editEventDescription">Event Details (Description)</label>\n                        <textarea id="editEventDescription" rows="3"></textarea>\n                    </div>\n                    <div class="form-group">\n                        <label for="editEventCapacity">Maximum Capacity Limit</label>\n                        <input type="number" id="editEventCapacity" placeholder="Leave empty or 0 for unlimited" min="0">\n                    </div>';
text = text.replace(s2, r2);

const s3 = '<div>\n                            <label style="display:block;font-size:11px;font-weight:700;color:var(--muted, #6b7280);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px;">Organizer</label>\n                            <input type="text" id="adsOrganizer" required value="Barangay Council"\n                                style="width:100%;padding:10px 14px;background:var(--bg, #f9fafb);border:1.5px solid var(--border, #e5e7eb);color:var(--text, #0f172a);border-radius:12px;font-size:14px;font-family:inherit;outline:none;box-sizing:border-box;transition:all 0.2s;"\n                                onfocus="this.style.borderColor=\'#3b82f6\'" onblur="this.style.borderColor=\'var(--border, #e5e7eb)\'">\n                        </div>';
const r3 = s3 + '\n\n                        <div>\n                            <label style="display:block;font-size:11px;font-weight:700;color:var(--muted, #6b7280);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px;">Event Details (Description)</label>\n                            <textarea id="adsEventDescription" placeholder="e.g., Free vaccine drive for residents" rows="3"\n                                style="width:100%;padding:10px 14px;background:var(--bg, #f9fafb);border:1.5px solid var(--border, #e5e7eb);color:var(--text, #0f172a);border-radius:12px;font-size:14px;font-family:inherit;outline:none;box-sizing:border-box;resize:vertical;transition:all 0.2s;"\n                                onfocus="this.style.borderColor=\'#3b82f6\'" onblur="this.style.borderColor=\'var(--border, #e5e7eb)\'"></textarea>\n                        </div>\n\n                        <div>\n                            <label style="display:block;font-size:11px;font-weight:700;color:var(--muted, #6b7280);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px;">Max Capacity Limit</label>\n                            <input type="number" id="adsEventCapacity" placeholder="Leave empty for unlimited" min="0"\n                                style="width:100%;padding:10px 14px;background:var(--bg, #f9fafb);border:1.5px solid var(--border, #e5e7eb);color:var(--text, #0f172a);border-radius:12px;font-size:14px;font-family:inherit;outline:none;box-sizing:border-box;transition:all 0.2s;"\n                                onfocus="this.style.borderColor=\'#3b82f6\'" onblur="this.style.borderColor=\'var(--border, #e5e7eb)\'">\n                        </div>';
text = text.replace(s3, r3);

const s4 = 'title: document.getElementById(\'eventTitle\').value,\n                    date: document.getElementById(\'eventDate\').value,\n                    time: document.getElementById(\'eventTime\').value,\n                    end_time: document.getElementById(\'eventEndTime\').value,\n                    organizer: document.getElementById(\'eventOrganizer\').value,\n                    location: document.getElementById(\'eventLocation\').value';
const r4 = s4 + ',\n                    description: document.getElementById(\'eventDescription\').value,\n                    capacity: parseInt(document.getElementById(\'eventCapacity\').value || \'0\', 10)';
text = text.replace(s4, r4);

const s5 = 'title: document.getElementById(\'editEventTitle\').value,\n                    date: document.getElementById(\'editEventDate\').value,\n                    time: document.getElementById(\'editEventTime\').value,\n                    end_time: document.getElementById(\'editEventEndTime\').value,\n                    organizer: document.getElementById(\'editEventOrganizer\').value,\n                    location: document.getElementById(\'editEventLocation\').value';
const r5 = s5 + ',\n                    description: document.getElementById(\'editEventDescription\').value,\n                    capacity: parseInt(document.getElementById(\'editEventCapacity\').value || \'0\', 10)';
text = text.replace(s5, r5);

const s6 = 'const eventData = {\n                    title: title + (cleanupMins > 0 ? ` (+${cleanupMins}m cleanup)` : \'\'),\n                    date: dateStr,\n                    time: startTime,\n                    end_time: endT,\n                    organizer: document.getElementById(\'adsOrganizer\').value,\n                    location: venue === \'basketball\' ? \'Basketball Court\' : \'Multi-Purpose Hall\',\n                    status: \'approved\'\n                };';
const r6 = 'const eventData = {\n                    title: title + (cleanupMins > 0 ? ` (+${cleanupMins}m cleanup)` : \'\'),\n                    date: dateStr,\n                    time: startTime,\n                    end_time: endT,\n                    organizer: document.getElementById(\'adsOrganizer\').value,\n                    location: venue === \'basketball\' ? \'Basketball Court\' : \'Multi-Purpose Hall\',\n                    description: document.getElementById(\'adsEventDescription\') ? document.getElementById(\'adsEventDescription\').value : \'\',\n                    capacity: document.getElementById(\'adsEventCapacity\') ? parseInt(document.getElementById(\'adsEventCapacity\').value || \'0\', 10) : 0,\n                    status: \'approved\'\n                };';
text = text.replace(s6, r6);

const s7 = 'document.getElementById(\'editEventLocation\').value = event.location;';
const r7 = s7 + '\n                    document.getElementById(\'editEventDescription\').value = event.description || \'\';\n                    document.getElementById(\'editEventCapacity\').value = event.capacity || \'\';';
text = text.replace(s7, r7);

// Side bar formatting fixes
const s8 = 'title: document.getElementById(\'adminSidebarEventTitle\').value,\n                date: document.getElementById(\'adminSidebarEventDate\').value,\n                time: document.getElementById(\'adminSidebarEventTime\').value,\n                end_time: document.getElementById(\'adminSidebarEventEndTime\').value,\n                organizer: document.getElementById(\'adminSidebarEventOrganizer\').value,\n                location: document.getElementById(\'adminSidebarEventLocation\').value';
const r8 = s8 + ',\n                description: document.getElementById(\'adminSidebarEventDesc\') ? document.getElementById(\'adminSidebarEventDesc\').value : \'\',\n                capacity: document.getElementById(\'adminSidebarEventCapacity\') ? parseInt(document.getElementById(\'adminSidebarEventCapacity\').value || \'0\', 10) : 0';
text = text.replace(s8, r8);

fs.writeFileSync('admin.html', text);
