import re

path = r'c:\Users\Kael\OneDrive\Documents\barangay-website\user-portal\user-dashboard.html'
with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Replace lines 3053-3092 (1-indexed) = indices 3052 to 3091 inclusive
start_idx = 3052
end_idx = 3091

new_code = (
    '        function _parseConcernResponse(response) {\n'
    '            if (!response) return { reply: null, log: [] };\n'
    '            if (typeof response === \'string\' && response.trim().startsWith(\'{\')) {\n'
    '                try { const p = JSON.parse(response); return { reply: p.reply || null, log: Array.isArray(p.log) ? p.log : [] }; } catch(e) {}\n'
    '            }\n'
    '            return { reply: response, log: [] };\n'
    '        }\n'
    '\n'
    '        function _concernStatusLabel(status) {\n'
    '            if (!status || status === \'pending\' || status === \'open\') return \'Submitted\';\n'
    '            if (status === \'in-progress\' || status === \'in_progress\') return \'In Progress\';\n'
    '            if (status === \'resolved\' || status === \'closed\') return \'Resolved\';\n'
    '            if (status === \'rejected\') return \'Rejected\';\n'
    '            return status;\n'
    '        }\n'
    '\n'
    '        function _concernStatusBadge(status) {\n'
    '            const label = _concernStatusLabel(status);\n'
    '            const styles = {\n'
    '                \'Submitted\':   \'background:#fef3c7;color:#92400e;border:1px solid #fde68a;\',\n'
    '                \'In Progress\': \'background:#dbeafe;color:#1e40af;border:1px solid #bfdbfe;\',\n'
    '                \'Resolved\':    \'background:#d1fae5;color:#065f46;border:1px solid #6ee7b7;\',\n'
    '                \'Rejected\':    \'background:#fee2e2;color:#991b1b;border:1px solid #fca5a5;\',\n'
    '            };\n'
    '            const s = styles[label] || \'background:#f1f5f9;color:#374151;border:1px solid #e2e8f0;\';\n'
    '            const icons = { \'Submitted\':\'&#128221;\', \'In Progress\':\'&#128260;\', \'Resolved\':\'&#10003;\', \'Rejected\':\'&#10060;\' };\n'
    '            return \'<span style="display:inline-flex;align-items:center;gap:4px;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:700;\' + s + \'">\' + (icons[label]||\'\') + \' \' + label + \'</span>\';\n'
    '        }\n'
    '\n'
    '        async function loadConcernsView() {\n'
    '            const concerns = await getMyConcerns();\n'
    '            const container = document.getElementById(\'myConcernsList\');\n'
    '            if (!concerns || concerns.length === 0) {\n'
    '                container.innerHTML = \'<p class="text-gray-500 italic py-4 col-span-full">You have not submitted any concerns yet.</p>\';\n'
    '                return;\n'
    '            }\n'
    '            const sorted = [...concerns].sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));\n'
    '            container.innerHTML = sorted.map(c => {\n'
    '                const statusBadge = _concernStatusBadge(c.status);\n'
    '                const parsed = _parseConcernResponse(c.response);\n'
    '                let actualDescription = c.description || \'No description provided\';\n'
    '                let attachedImageHtml = \'\';\n'
    '                if (actualDescription.includes(\'[ATTACHED_IMAGE_DATA]\')) {\n'
    '                    const parts = actualDescription.split(\'[ATTACHED_IMAGE_DATA]\');\n'
    '                    actualDescription = parts[0].replace(/Usern/g, \'\').trim();\n'
    '                    const b64 = parts[1].replace(/Usern/g, \'\').trim();\n'
    '                    attachedImageHtml = \'<div class="mt-2"><img src="\' + b64 + \'" class="max-h-24 rounded-lg border shadow-sm object-cover" alt="Attached photo"></div>\';\n'
    '                }\n'
    '                const repliedBadge = parsed.reply\n'
    '                    ? \'<span style="display:inline-flex;align-items:center;gap:3px;padding:2px 8px;border-radius:20px;font-size:10px;font-weight:700;background:#ecfdf5;color:#065f46;border:1px solid #6ee7b7;">&#10003; Replied</span>\'\n'
    '                    : \'\';\n'
    '                const fmtTs = ts => ts ? new Date(ts).toLocaleString(\'en-US\',{month:\'short\',day:\'numeric\',year:\'numeric\',hour:\'numeric\',minute:\'2-digit\'}) : \'\';\n'
    '                const submittedEntry = \'<div style="display:flex;gap:10px;align-items:flex-start;"><div style="width:8px;height:8px;border-radius:50%;background:#f59e0b;margin-top:4px;flex-shrink:0;"></div><div><span style="font-size:11px;font-weight:700;color:#92400e;">Submitted</span><span style="font-size:10px;color:#94a3b8;margin-left:6px;">\' + fmtTs(c.createdAt) + \'</span></div></div>\';\n'
    '                const logEntries = parsed.log.map(entry => {\n'
    '                    const ts = fmtTs(entry.timestamp);\n'
    '                    if (entry.action === \'status_changed\') {\n'
    '                        const dot = entry.status === \'resolved\' || entry.status === \'closed\' ? \'#10b981\' : entry.status === \'rejected\' ? \'#ef4444\' : \'#3b82f6\';\n'
    '                        return \'<div style="display:flex;gap:10px;align-items:flex-start;"><div style="width:8px;height:8px;border-radius:50%;background:\' + dot + \';margin-top:4px;flex-shrink:0;"></div><div><span style="font-size:11px;font-weight:700;color:var(--text-main);">Status: \' + _concernStatusLabel(entry.status) + \'</span><span style="font-size:10px;color:#94a3b8;margin-left:6px;">\' + ts + \'</span></div></div>\';\n'
    '                    }\n'
    '                    if (entry.action === \'replied\') {\n'
    '                        return \'<div style="display:flex;gap:10px;align-items:flex-start;"><div style="width:8px;height:8px;border-radius:50%;background:#10b981;margin-top:4px;flex-shrink:0;"></div><div><span style="font-size:11px;font-weight:700;color:#065f46;">Admin replied</span><span style="font-size:10px;color:#94a3b8;margin-left:6px;">\' + ts + \'</span></div></div>\';\n'
    '                    }\n'
    '                    return \'\';\n'
    '                }).filter(Boolean);\n'
    '                const timelineHtml = (parsed.log.length > 0)\n'
    '                    ? \'<div style="margin-top:10px;padding:10px 12px;background:var(--input-bg,#f9fafb);border-radius:10px;border:1px solid var(--border-color);display:flex;flex-direction:column;gap:6px;"><div style="font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#94a3b8;margin-bottom:4px;">Activity</div>\' + submittedEntry + logEntries.join(\'\') + \'</div>\'\n'
    '                    : \'\';\n'
    '                const replyHtml = parsed.reply\n'
    '                    ? \'<div style="background:#ecfdf5;border-left:4px solid #10b981;padding:10px 12px;border-radius:0 10px 10px 0;margin-top:10px;"><p style="margin:0 0 4px;font-size:11px;font-weight:800;color:#065f46;">Admin Response:</p><p style="margin:0;font-size:13px;color:#065f46;line-height:1.5;">\' + parsed.reply + \'</p></div>\'\n'
    '                    : \'\';\n'
    '                const isPending = !c.status || c.status === \'pending\' || c.status === \'open\';\n'
    '                return \'<div class="p-4 rounded-xl border hover:shadow-md transition-shadow bg-white dark:bg-gray-800 flex flex-col" style="border-color:var(--border-color);">\' +\n'
    '                    \'<div class="flex justify-between items-start gap-2 mb-2">\' +\n'
    '                    \'<h4 class="font-bold text-base line-clamp-1" style="color:var(--text-main);">\' + c.title + \'</h4>\' +\n'
    '                    \'<div style="display:flex;flex-direction:column;align-items:flex-end;gap:4px;flex-shrink:0;">\' + statusBadge + repliedBadge + \'</div>\' +\n'
    '                    \'</div>\' +\n'
    '                    \'<p class="text-xs opacity-80 mb-1" style="color:var(--text-main);">\' + actualDescription + \'</p>\' +\n'
    '                    attachedImageHtml +\n'
    '                    \'<div class="flex items-center justify-between mt-3 pt-3 border-t" style="border-color:var(--border-color);">\' +\n'
    '                    \'<div class="flex items-center gap-3 text-xs" style="color:var(--text-muted);"><span class="bg-gray-100 dark:bg-gray-700 px-2 py-0.5 rounded">\' + c.category + \'</span><span>&#128197; \' + formatDate(c.createdAt) + \'</span></div>\' +\n'
    '                    (isPending ? \'<div class="flex gap-2"><button onclick="openEditConcernModal(\' + c.id + \')" class="text-xs text-blue-500 hover:text-blue-700 font-semibold bg-blue-50 px-2 py-1 rounded">Edit</button><button onclick="deleteMyConcern(\' + c.id + \')" class="text-xs text-red-500 hover:text-red-700 font-semibold bg-red-50 px-2 py-1 rounded">Delete</button></div>\' : \'\') +\n'
    '                    \'</div>\' +\n'
    '                    timelineHtml +\n'
    '                    replyHtml +\n'
    '                    \'</div>\';\n'
    '            }).join(\'\');\n'
    '        }\n'
)

new_lines = lines[:start_idx] + [new_code] + lines[end_idx+1:]

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print(f'Replaced lines {start_idx+1}-{end_idx+1}. New total lines: {len(new_lines)}')
